### ISSUE TITLE
Support Julia 0.7 nightly

### ISSUE THREAD

**Issue by omus** [invenia/Dispatcher.jl#23]
Any reason the [Julia 0.7 pre-release](https://github.com/invenia/Dispatcher.jl/blob/master/REQUIRE#L1) isn't supported?

**Comment by iamed2** [comment]
It's a moving target and parallel semantics are changing slightly all the time. I didn't want to spend any time on 0.7 test failures until it hit alpha and I wanted to communicate that to users and devs.

**Comment by omus** [comment]
Ok, thanks.

**Comment by rofinn** [comment]
I don't think we're planning it, but if we wanted to move the package (e.g., under JuliaParallel) having an upper bound is useful.
