### ISSUE TITLE
Refactor DispatchContext to construct graph on demand

### ISSUE THREAD

**Issue by iamed2** [invenia/Dispatcher.jl#24]
We don't have to build the graph until right before we run it. This may heavily simplify the graph construction process and remove the need for `@node`.

**Comment by sbromberger** [comment]
I don't know whether this is relevant (either to this issue or to the package in general) but it seems to me after a cursory look that [MetaGraphs.jl](https://github.com/JuliaGraphs/MetaGraphs.jl) might be useful.

**Comment by iamed2** [comment]
This is definitely relevant to the package! This issue isn't the right place though. I'll make a new one.

**Comment by iamed2** [comment]
@sbromberger https://github.com/invenia/Dispatcher.jl/issues/29
