### ISSUE TITLE
@op equality check different on 0.7/1.0

### ISSUE THREAD

**Issue by nicoleepp** [invenia/Dispatcher.jl#39]
On 0.7:
```julia
julia> using Dispatcher

julia> ex1 = :(n1 = @op(1 + 2))
:(n1 = #= REPL[11]:1 =# @op(1 + 2))

julia> ex2 = :(n1 = @op(1 + 2))
:(n1 = #= REPL[12]:1 =# @op(1 + 2))

julia> ex1 == ex2
false
```

On 0.6:
```julia
julia> using Dispatcher

julia> ex1 = :(n1 = @op(1 + 2))

:(n1 = @op(1 + 2))

julia> ex2 = :(n1 = @op(1 + 2))
:(n1 = @op(1 + 2))

julia> ex1 == ex2
true
```

Can we make the behaviour be the same on 0.7 as it was on 0.6 (as in, disregard the LineNumberNode)?

**Comment by iamed2** [comment]
There's a function to strip this info but I forget what. Maybe @ararslan remembers?

**Comment by nicoleepp** [comment]
Base.remove_linenums! ?

Source: https://stackoverflow.com/questions/53274001/generic-function-for-stripping-linenumbernode-in-exprshould-be-able-to-deal

**Comment by iamed2** [comment]
Yep

**Comment by ararslan** [comment]
I don't know that `remove_linenums!` correctly handles macro calls. For something that's fully recursive and handles macros, you can use what I hacked into the Nabla tests to deal with comparing expressions: https://github.com/invenia/Nabla.jl/blob/master/test/code_transformation/differentiable.jl#L1-L13

**Comment by ararslan** [comment]
The Nabla code that generates `macrocall` expressions was also changed to always omit line number information on construction, since in that context the only line info you have access to is not useful.
